### ISSUE TITLE
Nether lighting very wrong

### ISSUE THREAD

**Issue by leagris** [jellysquid3/phosphor-forge#20]
##### Versions:

phosphor-1.12.2-0.2.4+build46-universal
forge-1.12.2-14.23.5.2838-universal.jar

##### Aspect of the lighting bug in Nether:

![2019-06-05_21 11 31](https://user-images.githubusercontent.com/1111474/58983247-b15e2900-87d6-11e9-865f-7dbc5e25e0cd.png)

##### Logs:

[fml-client-latest.log](https://github.com/jellysquid3/Phosphor/files/3258697/fml-client-latest.log)
[latest.log](https://github.com/jellysquid3/Phosphor/files/3258698/latest.log)

**Comment by jellysquid3** [comment]
I'm able to reproduce this on new worlds as well.

**Comment by jellysquid3** [comment]
This issue is caused by Sponge's async lighting patches. Please disable these patches in your Sponge configuration file. Future versions of Phosphor will refuse to run if these patches are enabled.

**Comment by leagris** [comment]
@jellysquid3 Where did you find Sponge lighting patch in the log I provided.
How is it possible since I run standard Forge and not Sponge?

**Comment by jellysquid3** [comment]
Apologies for not being more clear. The latest release of Phosphor 0.2.5 seemingly resolves these errors in the Nether dimension (or at least leaves me unable to reproduce them.)  The only case which still reliably produces similar issues to this one are with Sponge's async lighting patch enabled.

**Comment by Techjar** [comment]
I'm experiencing this on 0.2.6 and Sponge is not installed. Here's my list of mods in case it helps: https://gist.github.com/Techjar/98cf4aebefc23c12c392bffd62a896ca

**Comment by Techjar** [comment]
It seems like maybe it only affects existing chunks before Phosphor was installed.

**Comment by leagris** [comment]
Or it could be related to coordinates related, like negative values being iterated off by one. Seriously it look well like lighting information is off by one since it affect chunk boundaries.

**Comment by jellysquid3** [comment]
@Techjar Could you upload an archive of the world file? I'd like to investigate

**Comment by Techjar** [comment]
Is it okay if I upload a truncated version of just the nether, containing only the affected regions? The world is pretty large and my connection is very slow, meaning it would take hours to upload the full thing.

**Comment by leagris** [comment]
Probably 1 region file of the nether and the level.dat file, both are needed

**Comment by Techjar** [comment]
Here's 6 regions of the affected area in the nether around my portal: https://qimg.techjargaming.com/f/38MeRu2y.7z
And level.dat because I forgot to include it: https://qimg.techjargaming.com/f/XW3ITNvN.dat

My portal is located at -424,59,-2096. I could not seem to encounter the issue when flying beyond these regions, so maybe it's only affecting existing regions?

**Comment by jellysquid3** [comment]
Thanks for the region files, and sorry for the delay in my responses. I've been away from home the last few days.

From a cursory glance, it seems the issue is that these chunks in the Nether were generated before Phosphor was installed and that the mod put them into an invalid state. I'm unable to reproduce the issue after re-generating the world with the uploaded `level.dat`. That said, this is still an issue I very well intend to fix, as Phosphor is intended to be safe to add to existing worlds without complications.

**Comment by Techjar** [comment]
Yeah that's what it seems like, but it seems weird since the lighting in those chunks was fine until I installed Phosphor. Why would Phosphor affect existing light data?

**Comment by jellysquid3** [comment]
Phosphor for Minecraft 1.12 is no longer supported and will not receive additional updates outside of those for maintenance sake.
