### ISSUE TITLE
Random missing chunks in floating-dim worlds with Phosphor installed

### ISSUE THREAD

**Issue by Tslat** [jellysquid3/phosphor-forge#62]
[Zip Video.zip](https://github.com/jellysquid3/Phosphor/files/4322694/Zip.Video.zip)
![Modlist](https://user-images.githubusercontent.com/7098525/76495323-54d51c00-6482-11ea-91c2-1bcc4eb62b73.png)

So there seems to be a somewhat-consistent issue (at least for some people) where chunks are just not showing on the client. It doesn't appear to be a rendering issue as even entities and blocks placed within the invisible chunk are not shown, so perhaps the entire chunk isn't even being synced to the client?

Possibly a chunk is taking long enough to load that it's missing the sync to the client?
![unknown](https://user-images.githubusercontent.com/7098525/76496334-8cdd5e80-6484-11ea-9460-658c6e1d9dab.png)

[Video 2.zip](https://github.com/jellysquid3/Phosphor/files/4322799/Video.2.zip)

Doesn't seem to be a mod conflict - AoA doesn't affect rendering, world/chunk-syncing, or packet control in any special way (except some very minor gui stuff, which was disabled at the time of test anyway)

Sorry for zipped-videos, github doesn't allow videos and my gifs were too big

**Comment by Tslat** [comment]
The only oddity I can maybe see from my side (If it's related to my mod at all) is that in an effort to reduce lighting lag, I only call to light the chunk if it contains a block - not sure if this could cause anything

https://github.com/Tslat/Advent-Of-Ascension/blob/6d16c83d633b55271981ce26c63f119313db4ac8/source/dimension/haven/ChunkGenHaven.java#L83

**Comment by Tslat** [comment]
Found the issue I think

It was this section in my chunkgen

![image](https://user-images.githubusercontent.com/7098525/77377008-a56f4200-6dbd-11ea-90e4-a7436ddd981f.png)

Replacing it with just the generic generateSkylightMap fixes it. May or may not be something you need to worry about on your side, not sure. But either way it's resolved for my side. 
Thanks!

**Comment by jellysquid3** [comment]
Phosphor works on the assumption that an initial call to generate the skylight map will always happen (which is the case for vanilla chunk generators and every other mod I've come across.) It appears that not doing so results in chunks being initialized incorrectly, resulting in rendering weirdness because they aren't marked as "ready".

I'm not entirely sure it's safe to skip the call to generate the chunk's skylight map even if nothing is in it, but I also don't have the code in front of me. There's probably not much that can be done about this on our side, but generating the skylight map shouldn't hurt performance too much.

**Comment by Tslat** [comment]
Yeah I figured as much.

The only reason I did this was to try and reduce overheads on packs without phosphor installed. Floating-dim worlds suffer heavily from lighting calculations and I'm trying to do whatever I can to improve performance. At the moment the best thing I can do is recommend to have phosphor installed since that seems to fix the lag issue, but any advice from yourself as to what I can additionally do on my side to help with people who don't use phosphor would be much appreciated

**Comment by jellysquid3** [comment]
My response is massively delayed on this -- but short of directly modifying the lighting engine there won't be much to help the performance issues with the lighting engine other than to generate them closer to the ground.

I'm going to go ahead and close this issue since the problem has now been resolved on your side. For future stumblers upon this issue, see https://github.com/jellysquid3/phosphor-forge/issues/62#issuecomment-602939763.
