### ISSUE TITLE
Phosphor crashes when Mixins 0.8+ is present

### ISSUE THREAD

**Issue by BrisingrAerowing** [jellysquid3/phosphor-forge#64]
It seems Mixin 0.8 completely breaks Phosphor, causing a crash before even launching the game.

[Game Output](https://gist.github.com/BrisingrAerowing/a989ea7b71d3c0d1152f20e44ee75824).

**Comment by Zoutelande** [comment]
The 1.12.2 version does not need mixin bootstrap as it comes with the correct version already.

**Comment by BrisingrAerowing** [comment]
Yes, but JEID just updated to Mixin 0.8 to fix issues with Spongeforge. That seems to be what's breaking things.

**Comment by jellysquid3** [comment]
It looks like that we will have to upgrade as well to maintain compatibility with the rest of the ecosystem. Each mod trying to ship its own versions of Mixins has been a constant source of pain in 1.12.x and accounts for 80% of the issues opened on this tracker.

But, the author of MixinBootstrap doesn't appear to want people to be using their mod as anything more than an temporary workaround, and only recently put downloads up on CurseForge after someone else seemingly forced their hand. It makes it a hard sell, depending a project that the author doesn't advocate use of in production.

**Comment by jellysquid3** [comment]
I believe this leaves us with two options, really... but I am willing to hear feedback from others.

- Update the embedded Mixin dependency in Phosphor to version 0.8. This will likely not work since the vast majority of mods on Minecraft 1.12 which use Mixins are currently _also_ embedding version 0.7.10 of the library. It will be effectively random which version gets loaded first, and conflicts will arise from each mod overwriting things in the classpath.
- Migrate Phosphor towards using MixinBootstrap. This might not be appreciated by the author of said bootstrapper. If we can get other mod authors to also move towards using MixinBootstrap, this would be the cleanest solution... otherwise it has the same problems as the solution above. In modern versions of Forge, this is what other mod authors have already started doing.

**Comment by janagyjr** [comment]
This is 100% the issue I'm having right now. My modpack has become unplayable due to this breakage (and I need both JEID and Phosphor). 

I made a gist of the console log [here](https://gist.github.com/janagyjr/2a48d0d2ca5d26471cec4625d6a92e11), though everyone seems to know the problem.

**Comment by Sunconure11** [comment]
I’d say update mixin to 0.8.

**Comment by jellysquid3** [comment]
I've uploaded Phosphor 0.2.7 to CurseForge (which is still pending review) to address this issue. It simply includes an updated version of Mixins 0.8.

**Comment by janagyjr** [comment]
I hate to say it, but I'm still having an issue, now I can't even get it to load the pack enough for a crash. Console log is [here](https://gist.github.com/janagyjr/8f4cd9c93af9d52140fabb76b8be14b1). I have this issue referenced [here](https://github.com/BooLaLaEnterprises/TCGs-Just-for-Fun-Pack/issues/7).

**Comment by BrisingrAerowing** [comment]
You likely have a mod that still uses an older Mixin version.

**Comment by Firenzeo** [comment]
> 
> 
> You likely have a mod that still uses an older Mixin version.

This is easy to understand for me, but when reading through any crashlogs, it never references which mod initializes the older version of mixin... 

Is there a surefire way to tell? So we can bug them instead of you?

**Comment by jellysquid3** [comment]
The problem here is that Phosphor is overwriting the implementation of Mixins provided by MixinBootstrap, which causes Java to trip up because Phosphor's implementation wasn't signed using the key that MixinBootstrap's was.

There's not really any way to fix this on our side other than to make Phosphor depend on MixinBootstrap, which as I've outlined above is probably not optimal for a number of reasons. Alternatively, you could remove MixinBootstrap and see if Phosphor's own version can bootstrap it for you.

**Comment by janagyjr** [comment]
That assumes I actually am using Mixinbootstrap specifically. It's _not_ part of the modlist. Any version of Mixinbootstrap is being implemented directly by the mods.

http://prntscr.com/rsm1kr

Which means...I'm screwed for now. Still. Thanks anyway jelly (:

**Comment by BrisingrAerowing** [comment]
Any line that looks like this:

`Loading tweaker org.spongepowered.asm.launch.MixinTweaker from More-Planets-1.12.2-2.1.10-GC238.jar`

Shows a mod that is loading mixin. The only ones I know that have updated are JEID, VanillaFix and Phosphor.

**Comment by janagyjr** [comment]
"Any version of Mixinbootstrap is being implemented directly by the mods."

**Comment by BrisingrAerowing** [comment]
This happens even without that.

**Comment by janagyjr** [comment]
You're being purposely thick, aren't you?

**Comment by jellysquid3** [comment]
Phosphor will clash with mods that include Mixins and make use of JAR signing (which is largely useless as-is, no idea why Forge pushes it.) There is nothing we can really do about this other than for the community to decide upon a standard for shipping Mixins.
